spring:
  application:
    name: spring-boot-monitoring-web

info:
  app:
    encoding: "UTF-8"
    java:
      source: "11"
      target: "11"

server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: "health, info, prometheus"
  endpoint:
    health:
      show-details: always
      show-components: always
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

